apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app-deployment
  namespace: python-app
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: saaida/my-python-app-for-jenkins:latest
        ports:
        - containerPort: 8000
